modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Llunarstack/Nitrium/issues"

[[mods]]
modId = "nitrium"
version = "${version}"
displayName = "Nitrium"
authors = "Snappy_YT"
description = '''
A performance mod with an adaptive quality governor, entity render culling, and server-side
tick/worldgen/lighting optimizations. Complements Sodium/Embeddium, Iris/Oculus and friends.
'''
logoFile = "assets/nitrium/icon.png"

[[mixins]]
config = "nitrium.mixins.json"

[[mixins]]
config = "nitrium.client.mixins.json"

[[dependencies.nitrium]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nitrium]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"
